### PR TITLE
Print2debug

### PR DESCRIPTION
**Pull request by verpeteren**
Previously a lot of printf and fprintf statements have been used for debugging purposes. 
This is discusesd in [issue 44](https://github.com/nidium/Nidium/issues/44) and prepared by [libapenetwork changes](https://github.com/nidium/libapenetwork/commit/6df84559145a6e72d0854359048872b33373d34e)

The 'tag' has been set to the 'namespace' and the message starts with '[filename]'.

Please note that the following defines 'might need some rework':
- [ ] [NLOG](https://github.com/nidium/Nidium/blob/master/src/Core/Utils.h#L222-L223)
- [ ] [DPRINT](https://github.com/nidium/Nidium/blob/master/src/Binding/JSModules.cpp#L38)
- [ ] [SPAM](https://github.com/nidium/Nidium/blob/master/src/AV/Audio.h#L33-L34)

### CODE REVIEW

**Comment by paraboul** [comment]
Hey @verpeteren 

Sorry, but this is not good.
Nidium should not directly use APE_ macro.

Also, the "tag" parameter should be used instead of manually specifying the "domain"

**Comment by verpeteren** [comment]
Since  changes https://github.com/nidium/Nidium/commit/48a98788be4db662643cfac3cecd53f418ea248a? Things are slightly different.

[ ] shall I update this PR acourding to the
Or
[]  shall I close this PR?

**Comment by efyx** [comment]
Updating it is fine, since there are already some work done, but : 
- Don't forget to merge master first
- Replace : 
    - `APE_DEBUG("Binding", "[JSCanvas] Drag event detected\n");` 
    - by `ndm_log(NDM_LOG_INFO, "JSCanvas", "Drag event detected")`
        - Don't use `Bindings` for the tag, but instead the name of class (or use a shared tag between files when it makes more sense. For instance the AV module)
        - Don't put `\n` at the end of the formated string
- I noticed that you replaced all the english contraction like "cannot" => "can not". While it's correct in english, the contraction form is more widely used, so I would like to stick to that.  
    > AskOxford : Both cannot and can not are acceptable spellings, but the first is much more usual. You would use can not when the ‘not’ forms part of another construction such as ‘not only.’

**Comment by efyx** [comment]
Thanks for updating the PR, I have noticed a few things : 
- Server is no longer compiling, you probably want to use `ndm_logf()` here
```
../src/Server/Server.cpp:135:51: error: too many arguments provided to

      function-like macro invocation

    ndm_log(NDM_LOG_INFO, "Server", nidium_ascii, NIDIUM_SERVER_VERSION...
```
- Some files include "Macros.h" which is not needed (it's included project wide)
- The files in ` src/Interface/osx/` and `src/Interface/linux/` are using APE macros, instead of nidium macros 
- You can remove all the `[AV]` prefix used in by the SPAM() macro

**Comment by paraboul** [comment]
`Server.cpp:135`. Do not use nidium_log here, APE is not event initalized at this point. Also, this is not a log! we don't want file and line to be printed here

**Comment by efyx** [comment]
I have pushed some final changes/corrections. 

This looks good to be. @paraboul can we merge this one ?

**Pull request merged**
